### PR TITLE
fix compilation issues

### LINKED ISSUE #24: Compilation error in Fortran code using GCC 10.3.0
I am trying to compile picsar with GCC 10.3.0. It produces the following error:

```
     25    
     26      304 |               bztile, .FALSE., l_lower_order_in_v_in, LVEC_fieldgathe,                &
     27          |                      1
     28    ......
     29     1092 |                 bztile , l4symtry_in, l_lower_order_in_v_in, lvect,                   &
     30          |                         2
  >> 31    Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/LOGICAL(8)).
     32    src/particle_pushers/particle_pusher_manager_3d.F90:318:23:
     33    
     34      318 |               bztile , .FALSE., l_lower_order_in_v_in, lvec_fieldgathe,               &
     35          |                       1
     36    ......
     37     1104 |                 bztile , l4symtry_in, l_lower_order_in_v_in, lvect,                   &
     38          |                         2
  >> 39    Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/LOGICAL(8)).
  >> 40    make: *** [src/particle_pushers/particle_pusher_manager_3d.o] Error 1
```

It seems that it is caused due to some changes in GCC v10. It is possible to circumvent the error by adding '-fallow-argument-mismatch' to the Fortran compiler arguments.

### PR DESCRIPTION
**Pull request by lucafedeli88**
I have recently tried to compile PICSAR and I got two different error messages:
```
mpif90 -O3 -fopenmp -JModules -ftree-vectorize  -c -o src/field_solvers/Maxwell/yee_solver/yee.o src/field_solvers/Maxwell/yee_solver/yee.F90
src/field_solvers/Maxwell/yee_solver/yee.F90:541:46:

  541 |        if (tlo(1) <= 0 .and. 0 <= thi(1)) then
      |                                              1
Error: collapsed !$OMP DO loops not perfectly nested at (1)
src/field_solvers/Maxwell/yee_solver/yee.F90:589:46:

  589 |        if (zlo(1) <= 0 .and. 0 <= zhi(1)) then
      |                                              1
Error: collapsed !$OMP DO loops not perfectly nested at (1)
```
```
src/particle_pushers/particle_pusher_manager_3d.F90:304:22:

  304 |               bztile,  .FALSE., l_lower_order_in_v_in, LVEC_fieldgathe,                &
      |                      1
......
 1092 |                 bztile , l4symtry_in, l_lower_order_in_v_in, lvect,                   &
      |                         2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/LOGICAL(8)).
src/particle_pushers/particle_pusher_manager_3d.F90:318:23:

  318 |               bztile , .FALSE., l_lower_order_in_v_in, lvec_fieldgathe,               &
      |                       1
......
 1104 |                 bztile , l4symtry_in, l_lower_order_in_v_in, lvect,                   &
      |                         2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/LOGICAL(8)).
```

This PR should fix both issues: I have removed the `collapse(2)` clause from the OMP directives and I have  added the fix proposed by @dpgrote  in https://github.com/ECP-WarpX/picsar/issues/24

### CODE REVIEW

**Review by NeilZaim — APPROVED** [review]
Thanks for the fixes!

File: src/particle_pushers/particle_pusher_manager_3d.F90 [hunk 1]
```diff
@@ -301,7 +301,7 @@ SUBROUTINE field_gathering_plus_particle_pusher_sub(exg, eyg, ezg, bxg, byg, bzg
               curr_tile%nx_cells_tile, curr_tile%ny_cells_tile,                       &
               curr_tile%nz_cells_tile, nxjg, nyjg, nzjg, noxx, noyy, nozz,            &
               extile, eytile, eztile, bxtile, bytile,                                 &
-              bztile, .FALSE., l_lower_order_in_v_in, LVEC_fieldgathe,                &
+              bztile, logical(.FALSE., lp), l_lower_order_in_v_in, LVEC_fieldgathe,                &
```
Comment (NeilZaim) [inline src/particle_pushers/particle_pusher_manager_3d.F90:304]:
```suggestion
              bztile, logical(.FALSE., lp), l_lower_order_in_v_in, LVEC_fieldgathe,  &
```

File: src/particle_pushers/particle_pusher_manager_3d.F90 [hunk 2]
```diff
@@ -315,7 +315,7 @@ SUBROUTINE field_gathering_plus_particle_pusher_sub(exg, eyg, ezg, bxg, byg, bzg
               curr_tile%nx_cells_tile, curr_tile%ny_cells_tile,                       &
               curr_tile%nz_cells_tile, nxjg, nyjg, nzjg, noxx, noyy, nozz,            &
               extile, eytile, eztile, bxtile, bytile,                                 &
-              bztile , .FALSE., l_lower_order_in_v_in, lvec_fieldgathe,               &
+              bztile , logical(.FALSE., lp), l_lower_order_in_v_in, lvec_fieldgathe,               &
```
Comment (NeilZaim) [inline src/particle_pushers/particle_pusher_manager_3d.F90:318]:
```suggestion
              bztile , logical(.FALSE., lp), l_lower_order_in_v_in, lvec_fieldgathe,  &
```

**Review by NeilZaim — COMMENTED** [review]
Actually, some small formatting
